### ISSUE TITLE
All SSO sessions open in same container `name Profile`

### ISSUE THREAD

**Issue by kiyose** [WTFender/aws-sso-extender#102]
### Extension Version

1.7.7

### Description

All sso sessions are being opened into the same container `name Profile` where name is a constant `name` and Profile is interpolated correctly.

![Screenshot 2024-02-01 at 1 56 36 PM](https://github.com/WTFender/aws-sso-extender/assets/45911/eeed33e9-0a54-45fe-92ca-6a4fe6308704)

### Browsers

Firefox

### OS

Mac

**Comment by WTFender** [comment]
hey @kiyose - I'm not able to reproduce this.

Could you check what your SSO console label is set to? It should be using this format.
<img width="500" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/e37d27dc-54b5-493e-8845-e6c918cec48e">

**Comment by kiyose** [comment]
Thank you. It was a permissions issue. For some reason the extension had lost permissions to make modifications on console pages.

**Comment by kiyose** [comment]
I'll add that this issue has resurfaced intermittently but I am unable to reproduce once it started working again.  It seems to be tied to changing the output format.  I updated from the standard `{{user}}/{{profile}} @ {{account}}` to
`{{accountName}}.{{profile}}`

**Comment by WTFender** [comment]
@kiyose ill keep this open, as I am seeing some other odd behavior with unexpected console labels - feel free to add any details if you start seeing a pattern.

**Comment by jutley** [comment]
I got this error, but in my case the issue seemed to be tied to AWS SSO Containers. I didn't realize that this plugin could open in containers, so I used both plugins in conjunction.

To resolve the error with AWS SSO Containers, I had to open the AWS SSO homepage, and that seemed to somehow refresh AWS SSO Container's understanding of the different account names. Maybe that is the same issue as what happened in this extension.

**Comment by WTFender** [comment]
@jutley Thank you for the info!

The functionality between my extension and the wonderful AWS SSO Containers is very similar; the maintainer over there actually pointed me to the code he uses, so it's heavily based on that.

The container setting is disabled by default because I anticipate so many folks are already using that extension & do expect colliding behavior.

I'd recommend using the built-in container setting if you can; it will label your containers with the SSO & IAM label formats that you have control over; this is necessary for some of the tab switching behavior.

**Comment by WTFender** [comment]
@kiyose any chance you have AWS SSO Containers enabled as well?
