### ISSUE TITLE
Add support for multiple "IAM Assume Roles" per SSO profile

### ISSUE THREAD

**Issue by LinguineCode** [WTFender/aws-sso-extender#132]
### Description

I love this chrome extension @WTFender thank you so much. Right now it supports just one additional _IAM Assume Roles_ per SSO profile. If I try to add a second, it overwrites the first.

Would you please consider adding support for many more `IAM Assume Roles`? I'm sure many of us have a need for that.

**Comment by syphernl** [comment]
I am facing the same issue.
If you edit the JSON in the extension's editor and add additional entries to `iamRoles` it works for a few seconds and then for some reason automatically gets removed and reverts to having only one IAM Role.

I use the IAM Assume Roles functionality to access "External AWS Accounts", so I need an IAM Role entry for each of them underneath our SSO Root account. 
UI-wise this will likely get very messy since it is quite a number of roles.

**Comment by WTFender** [comment]
Confirming this is high on my list to fix. Adding multiple IAM roles to a
profile was previously working, not sure when it broke.
